export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as PartnerCompanies } from './PartnerCompanies'

export { default as BootcampProcess } from './BootcampProcess'
export { default as WhyChoose } from './WhyChoose'
export { default as Community } from './Community'
export { default as FAQ } from './FAQ'
export { default as Testimonials } from './Testimonials'
export { default as StandToGain } from './StandToGain'
export { default as MissionVision } from './MissionVision'
export { default as Achievements } from './Achievements'
export { default as CommunityShowcase } from './CommunityShowcase'
export { default as ApplyBanner } from './ApplyBanner'
export { default as FooterCTA } from './FooterCTA'
export { default as Bootcamps } from './Bootcamps'